.\" Manpage for liesel
.\" Contact andrew@rail5.org to correct errors or typos.
.TH man 8 "23 January 2022" "10.0" "liesel man page"
.SH NAME
liesel \- Transform ordinary PDFs into booklets
.SH SYNOPSIS
liesel -i some-book.pdf -o ready-to-print.pdf
.SH DESCRIPTION
Liesel prepares an inputted PDF to be DIY printed at home in pamphlet- or booklet-style
.SH OPTIONS
  -i
  --input
    PDF to convert

  -o
  --output
    New file for converted PDF

  -I
  --stdin
    Read PDF from STDIN rather than file
    e.g: liesel -I -o output.pdf < input.pdf

  -O
  --stdout
    Write output PDF to STDOUT rather than file
    e.g: liesel -i input.pdf -O > output.pdf

  -e
  --export
    Export example/preview JPEG image of selected pages
    e.g: -i infile.pdf -e 5,6 -o preview.jpeg
    e.g: --input infile.pdf --export 5,6 --output preview.jpeg

  -g
  --greyscale
  --grayscale
    Convert PDF to greyscale/black and white

  -r
  --range
    Print only specified range of pages (in the order supplied)
    e.g: -r 1-12
    e.g: --range 15-20,25-30
    e.g: -r 10,9,5,2,1
    e.g: --range 20-10
    
    The -r option will process only the selection you give, and in the order that you give it
    "-r 1,2,3,4,5" is the same as "-r 1-5"
    "-r 5-1" will print those pages in descending order

    You can also combine ranges using commas:
    -r 1-5,20-25,7,5-1
    will print first 1,2,3,4,5
    then 20,21,22,23,24,25
    then 7
    then 5,4,3,2,1

  -s
  --segment
    Print output PDFs in segments of a given size
    e.g: -s 40
      (produces multiple PDFs of 40 pages each)

  -m
  --minsize
    Specify minimum segment size (default is 4)
    e.g: -m 8
    
    The minimum segment size is only used when printing in segments
    If, for example, you're printing 100 pages with -s 40
    then 2 segments of 40 + 1 "runoff" segment of 20 will be produced
    If, instead, you print those 100 pages with -s 40 -m 21
    then those 20 pages, since they don't meet the minimum segment size,
    will be tacked on to the previous segment,
    making 1 segment of 40 pages + 1 segment of 60

    If -m is not specified, it defaults to 4 pages

  -f
  --force
    Force overwrites
      (do not warn about files already existing)

  -v
  --verbose
    Verbose mode

  -b
  --bookthief
  --progress
    Show progress (percentage done)

  -d
  --density
  --quality
  --ppi
    Specify pixels-per-inch density/quality (default is 100)
    e.g: -d 200

  -t
  --transform
  --rescale
    Transform output PDF to print on a specific size paper
      e.g: -t 8.5x11
      or: -t 8.5x11
      or: -t 23x7
      etc

  -l
  --landscape
  --duplex
    Duplex printer "landscape" flipping compatibility
      (flips every other page)

  -k
  --threshold
    Convert to pure black-and-white (not grayscale) with given threshold value between 0-100
    e.g: -k 70
      will convert any color with brightness under 70% to pure black, and any brighter color to pure white
      this option is particularly useful in printing PDFs of scanned books with yellowed pages etc

  -C
  --crop
    Crop pages according to specified values
    e.g: -C 10,20,30,40
      order: left,right,top,bottom
      cuts 10% from the left side, 20% from the right side, etc

  -w
  --widen
    Widen center margins according to specified value
    e.g: -w 30
      (adds blank space between pages)

  -a
  --auto-widen
    Auto-widen center margins
    e.g: -a (completely automatic)
    e.g: -a 30 (auto, with a maximum of 30)
      (progressively widens center margins towards the middle of the booklet)
      (if -w / --widen is also specified, -w / --widen acts as the minimum margin)

  -D
  --divide
    Divide each page into two
      divides the left half and the right half into separate pages
      this option is particularly useful in printing PDFs of scanned books which haven't already separated the pages
  
  -N
  --no-booklet
  --linear
    Applies the changes requested (crop, color threshold, etc) and outputs linearly, without making a booklet
      all features can be used except for center-margin widening

  -p
  --pages
    Count pages of input PDF and exit

  -c
  --check
    Check validity of command, and do not execute
  
  -B
  --output-settings
    Prints the parameters/settings you've provided, in XML format, to STDOUT

  -h
  --help
    Print this help message

  -q
  --info
    Print program info

  -V
  --version
    Print version number

Example:
  liesel -i some-book.pdf -g -r 64-77 -f -d 150 -v -b -o ready-to-print.pdf
  liesel -i some-book.pdf -r 100-300,350-400,1-10 -s 40 -t 8.25x11.75 -m 16 -o ready-to-print.pdf
  liesel --input some-book.pdf --range 1,5,7,3,1,50 --landscape --output ready-to-print.pdf
  liesel -p some-book.pdf
  liesel -c -i some-book.pdf -o output.pdf
.SH SEE ALSO
bookthief
.SH BUGS
No known bugs.
.SH AUTHOR
rail5 (andrew@rail5.org)
